# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(397, 565)
        self.actionAbrir = QAction(MainWindow)
        self.actionAbrir.setObjectName(u"actionAbrir")
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 9, 191, 271))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 70, 53, 20))
        self.origen_X = QSpinBox(self.groupBox)
        self.origen_X.setObjectName(u"origen_X")
        self.origen_X.setGeometry(QRect(79, 70, 101, 20))
        self.origen_X.setWrapping(True)
        self.origen_X.setFrame(True)
        self.origen_X.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.origen_X.setMaximum(500)
        self.origen_X.setValue(0)
        self.origen_X.setDisplayIntegerBase(10)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(19, 190, 53, 20))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 150, 53, 20))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 53, 20))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(19, 110, 53, 20))
        self.label_24 = QLabel(self.groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(19, 230, 53, 20))
        self.destino_y = QSpinBox(self.groupBox)
        self.destino_y.setObjectName(u"destino_y")
        self.destino_y.setGeometry(QRect(79, 190, 101, 20))
        self.destino_y.setMaximum(500)
        self.vel = QSpinBox(self.groupBox)
        self.vel.setObjectName(u"vel")
        self.vel.setGeometry(QRect(79, 230, 101, 20))
        self.vel.setMaximum(500)
        self.destino_x = QSpinBox(self.groupBox)
        self.destino_x.setObjectName(u"destino_x")
        self.destino_x.setGeometry(QRect(79, 150, 101, 20))
        self.destino_x.setMaximum(500)
        self.origen_y = QSpinBox(self.groupBox)
        self.origen_y.setObjectName(u"origen_y")
        self.origen_y.setGeometry(QRect(79, 110, 101, 20))
        self.origen_y.setMaximum(500)
        self.id = QSpinBox(self.groupBox)
        self.id.setObjectName(u"id")
        self.id.setGeometry(QRect(80, 30, 101, 22))
        self.id.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.id.setMaximum(99999)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 280, 191, 241))
        self.red = QSpinBox(self.groupBox_2)
        self.red.setObjectName(u"red")
        self.red.setGeometry(QRect(80, 20, 81, 21))
        self.red.setMaximum(255)
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(19, -30, 61, 20))
        self.label_27 = QLabel(self.groupBox_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(40, 60, 61, 20))
        self.blue = QSpinBox(self.groupBox_2)
        self.blue.setObjectName(u"blue")
        self.blue.setGeometry(QRect(80, 100, 81, 21))
        self.blue.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.blue.setMaximum(255)
        self.blue.setSingleStep(1)
        self.label_28 = QLabel(self.groupBox_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(50, 100, 61, 20))
        self.label_26 = QLabel(self.groupBox_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(50, 20, 61, 20))
        self.agregar_inicio_button = QPushButton(self.groupBox_2)
        self.agregar_inicio_button.setObjectName(u"agregar_inicio_button")
        self.agregar_inicio_button.setGeometry(QRect(20, 140, 151, 23))
        self.green = QSpinBox(self.groupBox_2)
        self.green.setObjectName(u"green")
        self.green.setGeometry(QRect(80, 60, 81, 21))
        self.green.setMaximum(255)
        self.agregar_final_button = QPushButton(self.groupBox_2)
        self.agregar_final_button.setObjectName(u"agregar_final_button")
        self.agregar_final_button.setGeometry(QRect(20, 170, 151, 23))
        self.mostrar_button = QPushButton(self.groupBox_2)
        self.mostrar_button.setObjectName(u"mostrar_button")
        self.mostrar_button.setGeometry(QRect(20, 200, 151, 23))
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(230, 10, 151, 511))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 397, 21))
        self.menuAbrir = QMenu(self.menubar)
        self.menuAbrir.setObjectName(u"menuAbrir")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAbrir.menuAction())
        self.menuAbrir.addAction(self.actionAbrir)
        self.menuAbrir.addAction(self.actionGuardar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbrir.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
#if QT_CONFIG(shortcut)
        self.actionAbrir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Part\u00edculas", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Origen (X)", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Destino (Y)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Destino (X)", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Origen (Y)", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Color RGB:", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Color (RGB):", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Green", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.agregar_inicio_button.setText(QCoreApplication.translate("MainWindow", u"Agregar Inicio", None))
        self.agregar_final_button.setText(QCoreApplication.translate("MainWindow", u"Agregar Final", None))
        self.mostrar_button.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.menuAbrir.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
    # retranslateUi

