# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(878, 691)
        self.actionAbrir = QAction(MainWindow)
        self.actionAbrir.setObjectName(u"actionAbrir")
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.actionGuardar.setShortcutContext(Qt.ApplicationShortcut)
        self.actionGrafo = QAction(MainWindow)
        self.actionGrafo.setObjectName(u"actionGrafo")
        self.action_Amplitud = QAction(MainWindow)
        self.action_Amplitud.setObjectName(u"action_Amplitud")
        self.action_Profundidad = QAction(MainWindow)
        self.action_Profundidad.setObjectName(u"action_Profundidad")
        self.actionRecorrido = QAction(MainWindow)
        self.actionRecorrido.setObjectName(u"actionRecorrido")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 581, 641))
        self.Graficos = QWidget()
        self.Graficos.setObjectName(u"Graficos")
        self.graficos = QGraphicsView(self.Graficos)
        self.graficos.setObjectName(u"graficos")
        self.graficos.setGeometry(QRect(10, 10, 551, 541))
        self.dibujar_button = QPushButton(self.Graficos)
        self.dibujar_button.setObjectName(u"dibujar_button")
        self.dibujar_button.setGeometry(QRect(180, 570, 75, 23))
        self.limpiar_button = QPushButton(self.Graficos)
        self.limpiar_button.setObjectName(u"limpiar_button")
        self.limpiar_button.setGeometry(QRect(310, 570, 75, 23))
        self.tabWidget.addTab(self.Graficos, "")
        self.Tabla = QWidget()
        self.Tabla.setObjectName(u"Tabla")
        self.tabla = QTableWidget(self.Tabla)
        self.tabla.setObjectName(u"tabla")
        self.tabla.setGeometry(QRect(10, 10, 551, 481))
        self.buscar_line_edit = QLineEdit(self.Tabla)
        self.buscar_line_edit.setObjectName(u"buscar_line_edit")
        self.buscar_line_edit.setGeometry(QRect(10, 510, 331, 21))
        self.buscar_button = QPushButton(self.Tabla)
        self.buscar_button.setObjectName(u"buscar_button")
        self.buscar_button.setGeometry(QRect(360, 510, 91, 23))
        self.mostrar_tabla_button = QPushButton(self.Tabla)
        self.mostrar_tabla_button.setObjectName(u"mostrar_tabla_button")
        self.mostrar_tabla_button.setGeometry(QRect(470, 510, 91, 23))
        self.groupBox_6 = QGroupBox(self.Tabla)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 550, 331, 51))
        self.id_checkbox = QCheckBox(self.groupBox_6)
        self.id_checkbox.setObjectName(u"id_checkbox")
        self.id_checkbox.setGeometry(QRect(10, 20, 31, 17))
        self.distancia_checkbox = QCheckBox(self.groupBox_6)
        self.distancia_checkbox.setObjectName(u"distancia_checkbox")
        self.distancia_checkbox.setGeometry(QRect(120, 20, 61, 17))
        self.velocidad_checkbox = QCheckBox(self.groupBox_6)
        self.velocidad_checkbox.setObjectName(u"velocidad_checkbox")
        self.velocidad_checkbox.setGeometry(QRect(250, 20, 71, 17))
        self.tabWidget.addTab(self.Tabla, "")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(590, 270, 271, 71))
        self.red = QSpinBox(self.groupBox_2)
        self.red.setObjectName(u"red")
        self.red.setGeometry(QRect(40, 30, 51, 21))
        self.red.setMaximum(255)
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(19, -30, 61, 20))
        self.label_27 = QLabel(self.groupBox_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(100, 30, 31, 20))
        self.blue = QSpinBox(self.groupBox_2)
        self.blue.setObjectName(u"blue")
        self.blue.setGeometry(QRect(200, 30, 51, 21))
        self.blue.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.blue.setMaximum(255)
        self.blue.setSingleStep(1)
        self.label_28 = QLabel(self.groupBox_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(180, 30, 21, 20))
        self.label_26 = QLabel(self.groupBox_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 30, 31, 20))
        self.green = QSpinBox(self.groupBox_2)
        self.green.setObjectName(u"green")
        self.green.setGeometry(QRect(120, 30, 51, 21))
        self.green.setMaximum(255)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(590, 10, 271, 51))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 20, 31, 20))
        self.id = QSpinBox(self.groupBox)
        self.id.setObjectName(u"id")
        self.id.setGeometry(QRect(70, 20, 91, 22))
        self.id.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.id.setMaximum(99999)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(590, 70, 271, 61))
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 20, 21, 20))
        self.origen_X = QSpinBox(self.groupBox_3)
        self.origen_X.setObjectName(u"origen_X")
        self.origen_X.setGeometry(QRect(40, 20, 81, 20))
        self.origen_X.setWrapping(True)
        self.origen_X.setFrame(True)
        self.origen_X.setButtonSymbols(QAbstractSpinBox.PlusMinus)
        self.origen_X.setMaximum(500)
        self.origen_X.setValue(0)
        self.origen_X.setDisplayIntegerBase(10)
        self.origen_y = QSpinBox(self.groupBox_3)
        self.origen_y.setObjectName(u"origen_y")
        self.origen_y.setGeometry(QRect(170, 20, 81, 20))
        self.origen_y.setMaximum(500)
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 20, 21, 20))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(590, 140, 271, 61))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 20, 21, 20))
        self.destino_x = QSpinBox(self.groupBox_4)
        self.destino_x.setObjectName(u"destino_x")
        self.destino_x.setGeometry(QRect(40, 20, 81, 20))
        self.destino_x.setMaximum(500)
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(150, 20, 21, 20))
        self.destino_y = QSpinBox(self.groupBox_4)
        self.destino_y.setObjectName(u"destino_y")
        self.destino_y.setGeometry(QRect(170, 20, 81, 20))
        self.destino_y.setMaximum(500)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(590, 210, 271, 51))
        self.vel = QSpinBox(self.groupBox_5)
        self.vel.setObjectName(u"vel")
        self.vel.setGeometry(QRect(70, 20, 91, 20))
        self.vel.setMaximum(500)
        self.label_24 = QLabel(self.groupBox_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(40, 20, 21, 20))
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(590, 360, 271, 201))
        self.agregar_final_button = QPushButton(self.centralwidget)
        self.agregar_final_button.setObjectName(u"agregar_final_button")
        self.agregar_final_button.setGeometry(QRect(740, 580, 121, 23))
        self.agregar_inicio_button = QPushButton(self.centralwidget)
        self.agregar_inicio_button.setObjectName(u"agregar_inicio_button")
        self.agregar_inicio_button.setGeometry(QRect(590, 580, 121, 23))
        self.mostrar_button = QPushButton(self.centralwidget)
        self.mostrar_button.setObjectName(u"mostrar_button")
        self.mostrar_button.setGeometry(QRect(590, 610, 121, 23))
        self.generar_button = QPushButton(self.centralwidget)
        self.generar_button.setObjectName(u"generar_button")
        self.generar_button.setGeometry(QRect(740, 610, 121, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 878, 21))
        self.menuAbrir = QMenu(self.menubar)
        self.menuAbrir.setObjectName(u"menuAbrir")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAbrir.menuAction())
        self.menuAbrir.addAction(self.actionAbrir)
        self.menuAbrir.addAction(self.actionGuardar)
        self.menuAbrir.addAction(self.actionGrafo)
        self.menuAbrir.addAction(self.actionRecorrido)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbrir.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
#if QT_CONFIG(shortcut)
        self.actionAbrir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionGrafo.setText(QCoreApplication.translate("MainWindow", u"Generar grafo", None))
#if QT_CONFIG(shortcut)
        self.actionGrafo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.action_Amplitud.setText(QCoreApplication.translate("MainWindow", u"en Amplitud", None))
        self.action_Profundidad.setText(QCoreApplication.translate("MainWindow", u"en Profundidad", None))
        self.actionRecorrido.setText(QCoreApplication.translate("MainWindow", u"Recorrido de grafo", None))
#if QT_CONFIG(shortcut)
        self.actionRecorrido.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.dibujar_button.setText(QCoreApplication.translate("MainWindow", u"Dibujar", None))
        self.limpiar_button.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Graficos), QCoreApplication.translate("MainWindow", u"Gr\u00e1ficos", None))
        self.buscar_line_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID Particula", None))
        self.buscar_button.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.mostrar_tabla_button.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Ordenar por:", None))
        self.id_checkbox.setText(QCoreApplication.translate("MainWindow", u"Id", None))
        self.distancia_checkbox.setText(QCoreApplication.translate("MainWindow", u"Distancia", None))
        self.velocidad_checkbox.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tabla), QCoreApplication.translate("MainWindow", u"Tabla", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Color RGB:", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Color (RGB):", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"G:", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"B:", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"R:", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Part\u00edculas", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Coordenadas de Origen", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Coordenadas de Destino", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Vel:", None))
        self.agregar_final_button.setText(QCoreApplication.translate("MainWindow", u"Agregar Final", None))
        self.agregar_inicio_button.setText(QCoreApplication.translate("MainWindow", u"Agregar Inicio", None))
        self.mostrar_button.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.generar_button.setText(QCoreApplication.translate("MainWindow", u"Generar", None))
        self.menuAbrir.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
    # retranslateUi

